apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-postgres
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: quay.io/h0tbird/tva-postgres:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-tva
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
